version: "3"
services:
  # Servidor web
  application:
    image: srueda99/python-login:v3
    container_name: app-python
    command: python /app/main.py
    ports:
      - 80:80
    environment:
      - DB_HOST=database
      - DB_SCHEMA=login
      - DB_USER=root
      - DB_PASSWORD=toor
  
  # Base de datos
  database:
    image: mysql
    container_name: app-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=login
    volumes:
      - db-mysql:/var/lib/mysql

volumes:
  db-mysql:
    external: true