apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deploy
spec:
  selector:
    matchLabels:
      role: web
      app: node
  replicas: 3
  template:
    metadata:
      labels:
        role: web
        app: node
    spec:
      # Python container
      containers:
      - name: app-node
        image: srueda99/python-login
        # Environment variables
        env:
        - name: DB_HOST
          value: $(DB_SERVICE_HOST)
        - name: DB_USER
          value: root
        - name: DB_SCHEMA
          value: login
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-password
              key: password
        - name: PORT
          value: "80"
        # After build command
        command: ["python"]
        args: ["/app/main.py"]
        # HTTP Port
        ports:
        - containerPort: 80
        # Resources limit
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        # Availability tests
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20

---
# NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
  selector:
    role: web