apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
    app: node
spec:
  capacity:
    storage: 250Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi